#ifndef MCRESTOOL_FILETYPE_H
#define MCRESTOOL_FILETYPE_H

enum FileType {
    FILETYPE_NONE,
    FILETYPE_LANGUAGE,
    FILETYPE_LANGUAGE_PART,
    FILETYPE_RECIPE,
};

#endif //MCRESTOOL_FILETYPE_H
