[package]
name = "mcrestool-library-rs"
version = "0.1.0"
authors = ["2xsaiko <git@dblsaiko.net>"]
edition = "2018"

[dependencies]
cxx = "0.5"
zip = "0.5.8"
serde = "1.0.117"
serde_json = "1.0.59"
thiserror = "1.0.22"

[lib]
crate-type = ["staticlib"]

[profile.release]
lto = true