[package]
name = "mcrtlib-rs"
version = "0.1.0"
authors = ["2xsaiko <git@dblsaiko.net>"]
edition = "2018"

[features]
cpp = ["cxx"]

# only needed while corrosion doesn't allow specifying features yet
default = ["cpp"]

[dependencies]
# cxx = "1.0"
cxx = { git = "https://github.com/2xsaiko/cxx", branch = "mutu8", optional = true }
zip = "0.5.8"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
thiserror = "1.0.22"
byteorder = "*"
bincode = "1.3.1"
matryoshka = { path = "../matryoshka" }

[lib]
crate-type = ["staticlib"]