[package]
name = "mcrestool-library-rs"
version = "0.1.0"
authors = ["2xsaiko <git@dblsaiko.net>"]
edition = "2018"

[dependencies]
# cxx = "0.5"
cxx = { git = "https://github.com/2xsaiko/cxx", branch = "mutu8" }
zip = "0.5.8"
serde = "1.0.117"
serde_json = "1.0.59"
thiserror = "1.0.22"
pin-weak = "1.0.0"

[lib]
crate-type = ["staticlib"]

[profile.release]
lto = true