[package]
name = "mcrestool_logic"
version = "0.1.0"
authors = ["2xsaiko <git@dblsaiko.net>"]
edition = "2018"
build = "build.rs"

[profile.release]
lto = true

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.67"
zip = "0.5.4"

[build-dependencies]
cbindgen = "0.13.1"